apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-interface-docker
  labels:
    k0rdent.mirantis.com/aggregate-to-manager: "true"
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - dockerclusters
    verbs:
      - get
      - list
      - patch
      - watch
