apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-vsphere
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: VSphereCluster
  clusterIdentityKinds:
    - VSphereClusterIdentity
  description: "vSphere infrastructure provider for Cluster API"
