nameOverride: ""
fullnameOverride: ""

admissionWebhook:
  enabled: false
  port: 9443
  certDir: "/tmp/k8s-webhook-server/serving-certs/"

controller:
  defaultRegistryURL: "oci://ghcr.io/k0rdent/kcm/charts"
  registryCredsSecret: ""
  insecureRegistry: false
  createManagement: false
  createAccessManagement: false
  createRelease: false
  createTemplates: false
  enableTelemetry: false
  backup:
    requeuePeriod: 5m # TODO: probably no need, revisit

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

image:
  repository: ghcr.io/k0rdent/kcm/controller
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicas: 1

serviceAccount:
  annotations: {}

kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP

# Subcharts
cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false

flux2:
  enabled: true
  policies:
    create: false
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
  helmController:
    container:
      additionalArgs:
        - --watch-label-selector=hmc.mirantis.com/managed=true
  sourceController:
    container:
      additionalArgs:
        - --watch-label-selector=hmc.mirantis.com/managed=true

cluster-api-operator:
  enabled: false
  resources:
    manager:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 150Mi

# TODO: remove all of the imagePullSecrets, used for localhost DEBUG
velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.11.0
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - docker-registry
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-microsoft-azure
      image: velero/velero-plugin-for-microsoft-azure:v1.11.0
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - docker-registry
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-gcp
      image: velero/velero-plugin-for-gcp:v1.11.0
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - docker-registry
      volumeMounts:
        - mountPath: /target
          name: plugins
  image:
    imagePullSecrets:
    - docker-registry
  metrics:
    enabled: false
  upgradeCRDs: false
  cleanUpCRDs: false
  rbac:
    create: false
    clusterAdministrator: false
  serviceAccount:
    server:
      create: false
      imagePullSecrets:
      - docker-registry
  credentials:
    useSecret: false
  snapshotsEnabled: false
  backupsEnabled: false
  deployNodeAgent: false
