apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: azure
spec:
  version: v1.17.4
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  manager: {{- toYaml .Values.manager | nindent 4 }}
  manifestPatches:
    - |
      apiVersion: v1
      kind: Service
      metadata:
        name: azureserviceoperator-webhook-service
      spec:
        selector:
          control-plane: aso-controller-manager
    - |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: azureserviceoperator-controller-manager
      spec:
        selector:
          matchLabels:
            control-plane: aso-controller-manager
        template:
          metadata:
            labels:
              control-plane: aso-controller-manager
          spec:
            volumes:
            - name: cert
              secret:
                defaultMode: 420
                secretName: aso-webhook-server-cert
            - name: azure-identity
              projected:
                defaultMode: 420
                sources:
                - serviceAccountToken:
                    audience: api://AzureADTokenExchange
                    expirationSeconds: 3600
                    path: azure-identity
    - |
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: azureserviceoperator-serving-cert
      spec:
        secretName: aso-webhook-server-cert
