apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: adopted-cluster-1-0-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: adopted-cluster
      version: 1.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
