apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: adopted-cluster-0-0-2
  annotations:
    helm.sh/resource-policy: keep
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  helm:
    chartSpec:
      chart: adopted-cluster
      version: 0.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
