apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: aws-standalone-cp-1-0-9
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: aws-standalone-cp
      version: 1.0.9
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
