apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: aws-eks-1-0-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: aws-eks
      version: 1.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
