apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: aws-standalone-cp-0-0-5
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: aws-standalone-cp
      version: 0.0.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
