apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: aws-hosted-cp-0-1-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: aws-hosted-cp
      version: 0.1.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
