apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: azure-standalone-cp-1-0-8
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: azure-standalone-cp
      version: 1.0.8
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
