apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: azure-aks-0-1-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: azure-aks
      version: 0.1.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
