apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-vsphere-0-2-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-vsphere
      version: 0.2.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
