apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-1-0-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api
      version: 1.0.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
