apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-openstack-0-1-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-openstack
      version: 0.1.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
