apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-0-0-6
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api
      version: 0.0.6
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
