apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-aws-0-0-4
  annotations:
    helm.sh/resource-policy: keep
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-aws
      version: 0.0.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
