apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-aws-1-0-4
  annotations:
    helm.sh/resource-policy: keep
    {{- if has .TemplateName .Values.disabledTemplates }}
    k0rdent.mirantis.com/provider-disabled: "true"
    {{- end }}
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-aws
      version: 1.0.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
