apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: gcp-standalone-cp-1-0-5
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: gcp-standalone-cp
      version: 1.0.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
