apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: kcm-regional-1-0-5
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: kcm-regional
      version: 1.0.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
