apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: kcm-0-0-7
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: kcm
      version: 0.0.7
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
