apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: projectsveltos-0-54-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: projectsveltos
      version: 0.54.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
