apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: remote-cluster-0-1-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: remote-cluster
      version: 0.1.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
