apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: 3
  # dirty hack
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: {{ include "k0sconfig.name" . }}
      namespace: {{ .Release.Namespace }}
    spec:
      extensions:
        helm:
          repositories:
          - name: aws-cloud-controller-manager
            url: https://kubernetes.github.io/cloud-provider-aws
          charts:
          - name: aws-cloud-controller-manager
            namespace: kube-system
            chartname: aws-cloud-controller-manager/aws-cloud-controller-manager
            version: "0.0.8"
            values: |
              args:
                - --v=2
                - --cloud-provider=aws
                - --cluster-cidr={{ first .Values.clusterNetwork.pods.cidrBlocks }}
                - --allocate-node-cidrs=true
                - --cluster-name={{ include "cluster.name" . }}
              # Removing the default `node-role.kubernetes.io/control-plane` node selector
              # TODO: it does not work
              # nodeSelector: ""