apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  {{- if .Values.singleArtifactSource.enabled }}
  downloadURL: "{{ .Values.singleArtifactSource.k0sURL }}/k0s-{{ .Values.k0s.version }}-amd64"
  {{- end }}
  k0sConfigSpec:
    files:
      - path: /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
        permissions: "0600"
        content: "{{ trim .Values.controlPlane.ssh.publicKey }}"
    preStartCommands:
      - chown {{ .Values.controlPlane.ssh.user }} /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
      - sed -i 's/"externalAddress":"{{ .Values.controlPlaneEndpointIP }}",//' /etc/k0s.yaml
    args:
      - --enable-worker
      - --disable-components=konnectivity-server
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          sans:
            - {{ .Values.controlPlaneEndpointIP }}
          extraArgs:
            anonymous-auth: "true"
            {{- with .Values.k0s.api.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        network:
          provider: calico
          calico:
            mode: vxlan
        {{- if .Values.singleArtifactSource.enabled }}
        images:
          metricsserver:
            image: "{{ .Values.singleArtifactSource.registry}}/metrics-server"
          kubeproxy:
            image: "{{ .Values.singleArtifactSource.registry}}/kube-proxy"
          coredns:
            image: "{{ .Values.singleArtifactSource.registry}}/coredns"
          pause:
            image: "{{ .Values.singleArtifactSource.registry}}/pause"
          calico:
            cni:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-cni"
            node:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-node"
            kubecontrollers:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-kube-controllers"
        {{- end }}
        extensions:
          helm:
            {{- if not .Values.singleArtifactSource.enabled }}
            repositories:
            - name: kube-vip
              url: https://kube-vip.github.io/helm-charts
            - name: vsphere-cpi
              url: https://kubernetes.github.io/cloud-provider-vsphere
            - name: mirantis
              url: https://charts.mirantis.com
            {{- end }}
            charts:
            - name: kube-vip
              {{- if .Values.singleArtifactSource.enabled }}
              chartname: oci://{{ .Values.singleArtifactSource.registry}}/kube-vip
              {{- else }}
              chartname: kube-vip/kube-vip
              {{- end }}
              version: 0.6.1
              order: 1
              namespace: kube-system
              values: |
                {{- if .Values.singleArtifactSource.enabled }}
                image:
                  repository: {{ .Values.singleArtifactSource.registry }}/kube-vip
                {{- end }}
                config:
                  address: {{ .Values.controlPlaneEndpointIP }}
                env:
                  svc_enable: "true"
                  cp_enable: "true"
                  lb_enable: "false"
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
            - name: vsphere-cpi
              {{- if .Values.singleArtifactSource.enabled }}
              chartname: oci://{{ .Values.singleArtifactSource.registry}}/vsphere-cpi
              {{- else }}
              chartname: vsphere-cpi/vsphere-cpi
              {{- end }}
              version: 1.31.0
              order: 2
              namespace: kube-system
              values: |
                config:
                  enabled: false
                daemonset:
                  {{- if .Values.singleArtifactSource.enabled }}
                  image: {{ .Values.singleArtifactSource.registry }}/cloud-provider-vsphere
                  {{- end }}
                  tolerations:
                    - effect: NoSchedule
                      key: node.cloudprovider.kubernetes.io/uninitialized
                      value: "true"
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/master
                      operator: Exists
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/control-plane
                      operator: Exists
                    - effect: NoSchedule
                      key: node.kubernetes.io/not-ready
                      operator: Exists
                    - key: CriticalAddonsOnly
                      effect: NoExecute
                      operator: Exists
            - name: vsphere-csi-driver
              {{- if .Values.singleArtifactSource.enabled }}
              chartname: oci://{{ .Values.singleArtifactSource.registry}}/vsphere-csi-driver
              {{- else }}
              chartname: mirantis/vsphere-csi-driver
              {{- end }}
              version: 0.0.3
              order: 3
              namespace: kube-system
              values: |
                vcenterConfig:
                  enabled: false
                node:
                  kubeletPath: /var/lib/k0s/kubelet
                defaultStorageClass:
                  enabled: true
                images:
                  driver:
                    {{- if .Values.singleArtifactSource.enabled }}
                    repo: {{ .Values.singleArtifactSource.registry }}/driver
                    {{- end }}
                    tag: v3.1.2
                  syncer:
                    {{- if .Values.singleArtifactSource.enabled }}
                    repo: {{ .Values.singleArtifactSource.registry }}/syncer
                    {{- end }}
                    tag: v3.1.2
                  {{- if .Values.singleArtifactSource.enabled }}
                  nodeDriverRegistrar:
                    repo: {{ .Values.singleArtifactSource.registry }}/csi-node-driver-registrar
                  csiAttacher:
                    repo: {{ .Values.singleArtifactSource.registry }}/csi-attacher
                  csiResizer:
                    repo: {{ .Values.singleArtifactSource.registry }}/csi-resizer
                  csiProvisioner:
                    repo: {{ .Values.singleArtifactSource.registry }}/csi-provisioner
                  csiSnapshotter:
                    repo: {{ .Values.singleArtifactSource.registry }}/csi-snapshotter
                  livenessProbe:
                    repo: {{ .Values.singleArtifactSource.registry }}/livenessprobe
                  {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: {{ include "vspheremachinetemplate.controlplane.name" . }}
      namespace: {{ .Release.Namespace }}
