apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: v1.3.0
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if .Values.airgap }}
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: k0sproject-k0smotron
        provider.cluster.x-k8s.io/type: infrastructureprovider
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: v1.3.0
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if .Values.airgap }}
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: k0sproject-k0smotron
        provider.cluster.x-k8s.io/type: bootstrapprovider
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: k0sproject-k0smotron
spec:
  version: v1.3.0
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if .Values.airgap }}
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: k0sproject-k0smotron
        provider.cluster.x-k8s.io/type: controlplaneprovider
  {{- end }}
