apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.clusterLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterNetwork:
    {{- with .Values.clusterNetwork.pods }}
    pods:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.clusterNetwork.services }}
    services:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ .Release.Name }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Release.Name }}-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  controlPlaneLoadBalancer:
    {{- toYaml .Values.loadBalancer | nindent 4 }}
  region: {{ .Values.region }}
  sshKeys:
    - name: {{ .Values.sshKeyName }}
  network:
    {{- toYaml .Values.network | nindent 4 }}
  hetznerSecretRef:
    name: {{ .Values.clusterIdentity.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Release.Name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerMachineTemplate
      name: {{ .Release.Name }}-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerMachineTemplate
metadata:
  name: {{ .Release.Name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- with .Values.controlPlane }}
      type: {{ .serverType }}
      image: {{ .image }}
      {{- with .rootVolume }}
      rootVolume:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .placementGroup }}
      placementGroup:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Release.Name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Release.Name }}
  replicas: {{ .Values.workersNumber }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
      pool: worker
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
        pool: worker
    spec:
      clusterName: {{ .Release.Name }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Release.Name }}-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerMachineTemplate
        name: {{ .Release.Name }}-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerMachineTemplate
metadata:
  name: {{ .Release.Name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- with .Values.worker }}
      type: {{ .serverType }}
      image: {{ .image }}
      {{- with .rootVolume }}
      rootVolume:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .placementGroup }}
      placementGroup:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Release.Name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external 