apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    # This annotation is required to prevent the premature deletion
    # of GCPManagedCluster. Without it, GCPManagedCluster
    # may be deleted before the MachinePool, causing the MachinePool
    # deletion to get stuck due to the missing cluster.
    helm.sh/resource-policy: keep
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  project: {{ .Values.project }}
  region: {{ .Values.region }}
  network:
    name: {{ .Values.network.name }}
    mtu: {{ .Values.network.mtu }}
  {{- if .Values.additionalLabels }}
  additionalLabels: {{- toYaml .Values.additionalLabels | nindent 4 }}
  {{- end }}
  credentialsRef:
    name: {{ .Values.clusterIdentity.name }}
    namespace: {{ .Values.clusterIdentity.namespace }}
