apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: {{ include "gcpmanagedcontrolplane.name" . }}
spec:
  gkeClusterName: {{ .Values.gkeClusterName }}
  project: {{ .Values.project }}
  location: {{ .Values.location | default .Values.region }}
  enableAutopilot: {{ .Values.enableAutopilot }}
  releaseChannel: {{ .Values.releaseChannel }}
  {{- if .Values.controlPlaneVersion }}
  controlPlaneVersion: {{ .Values.controlPlaneVersion }}
  {{- end }}
  {{- if .Values.masterAuthorizedNetworksConfig }}
  master_authorized_networks_config: {{ .Values.masterAuthorizedNetworksConfig }}
  {{- end }}
