{{- if not .Values.enableAutopilot }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ include "machinepool.name" . }}
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.workersNumber }}
  template:
    spec:
      bootstrap:
        dataSecretName: {{ include "machinepool.name" . }}
      clusterName: {{ include "cluster.name" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPManagedMachinePool
        name: {{ include "machinepool.name" . }}
{{- end }}
