apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ include "awsmanagedcontrolplane.name" . }}
spec:
  eksClusterName: {{ .Values.eksClusterName }}
  region: {{ .Values.region }}
  {{- if not (quote .Values.sshKeyName | empty) }}
  sshKeyName: {{ .Values.sshKeyName | quote }}
  {{- end }}
  version: {{ .Values.kubernetes.version }}
  associateOIDCProvider: {{ .Values.associateOIDCProvider }}
  {{- with .Values.oidcIdentityProviderConfig }}
  oidcIdentityProviderConfig: {{- toYaml . | nindent 4 }}
  {{- end }}
  vpcCni:
    disable: {{ .Values.vpcCni.disable }}
    {{- if .Values.vpcCni.env }}
    env: {{- toYaml .Values.vpcCni.env | nindent 4}}
    {{- end }}
  kubeProxy:
    disable: {{ .Values.kubeProxy.disable }}
  identityRef:
    kind: {{ .Values.clusterIdentity.kind }}
    name: {{ .Values.clusterIdentity.name }}
  {{- with .Values.addons }}
  addons: {{- toYaml . | nindent 4 }}
  {{- end }}
