workersNumber: 1

clusterLabels: {}
clusterAnnotations: {}

clusterNetwork:
  pods:
    cidrBlocks:
    - "192.168.0.0/16"
  services:
    cidrBlocks:
    - "10.128.0.0/12"
  serviceDomain: "cluster.local"

# K0smotron parameters
k0smotron:
  service:
    type: NodePort

k0s:
  # NOTE: Update with caution – see: PR https://github.com/k0rdent/kcm/pull/1057#issuecomment-2668629616
  version: v1.32.1+k0s.0
