workersNumber: 1

clusterLabels: {}
clusterAnnotations: {}

clusterNetwork:
  pods:
    cidrBlocks:
    - "192.168.0.0/16"
  services:
    cidrBlocks:
    - "10.128.0.0/12"
  serviceDomain: "cluster.local"

# K0smotron parameters
k0smotron: # @schema description: K0smotron parameters; type: object
  controllerPlaneFlags: [] # @schema description: ControlPlaneFlags allows to configure additional flags for k0s control plane and to override existing ones. The default flags are kept unless they are overriden explicitly. Flags with arguments must be specified as a single string, e.g. --some-flag=argument; type: array; item: string; uniqueItems: true
  service: # @schema description: The API service configuration; type: object
    type: NodePort # @schema description: An ingress methods for a service; type: string; enum: ClusterIP, NodePort, LoadBalancer; default: NodePort

# K0s parameters
k0s: # @schema description: K0s parameters; type: object
  # NOTE: Update with caution – see: PR https://github.com/k0rdent/kcm/pull/1057#issuecomment-2668629616
  version: v1.32.1+k0s.0 # @schema description: K0s version; type: string
  workerArgs: [] # @schema description: Args specifies extra arguments to be passed to k0s worker. See: https://docs.k0sproject.io/stable/worker-node-config/ See: https://docs.k0sproject.io/stable/cli/k0s_worker/; type: array; item: string; uniqueItems: true
