# Cluster parameters
controlPlaneNumber: 3
workersNumber: 2

ipamEnabled: false

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"

clusterLabels: {}
clusterAnnotations: {}

# vSphere cluster parameters
clusterIdentity:
  name: ""
vsphere:
  server: ""
  thumbprint: ""
  datacenter: ""
  datastore: ""
  resourcePool: ""
  folder: ""
controlPlaneEndpointIP: ""
nameservers: []

# vSphere machines parameters
controlPlane:
  ssh:
    user: ""
    publicKey: ""
  rootVolumeSize: 30
  cpus: 2
  memory: 4096
  vmTemplate: ""
  network: ""

worker:
  ssh:
    user: ""
    publicKey: ""
  rootVolumeSize: 30
  cpus: 2
  memory: 4096
  vmTemplate: ""
  network: ""

# K0s parameters
k0s: # @schema description: K0s parameters; type: object
  version: v1.32.5+k0s.1 # @schema description: K0s version; type: string
  cpArgs: [] # @schema description: Args specifies extra arguments to be passed to k0s controller. See: https://docs.k0sproject.io/stable/cli/k0s_controller/; type: array; item: string; uniqueItems: true
  workerArgs: [] # @schema description: Args specifies extra arguments to be passed to k0s worker. See: https://docs.k0sproject.io/stable/worker-node-config/ See: https://docs.k0sproject.io/stable/cli/k0s_worker/; type: array; item: string; uniqueItems: true
  api: # @schema description: Kubernetes API server parameters; type: object
    extraArgs: {} # @schema description: Map of key-values (strings) for any extra arguments to pass down to Kubernetes api-server process; type: object; additionalProperties: true

