{{- $global := .Values.global | default dict }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
spec:
  template:
    spec:
      {{- if $global.k0sURL }}
      downloadURL: "{{ $global.k0sURL }}/k0s-{{ .Values.k0s.version }}-amd64"
      {{- end }}
      version: {{ .Values.k0s.version }}
      args:
      - --enable-cloud-provider
      - --kubelet-extra-args="--cloud-provider=external"
