apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-capi-identities-viewer-role
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - awsclusterroleidentities
      - awsclusterstaticidentities
      - azureclusteridentities
      - vsphereclusteridentities
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
