apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-servicetemplatechains-creator-role
rules:
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - servicetemplatechains
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
      - create
      - delete
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - servicetemplates
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
