{{- $global := .Values.global | default dict }}
{{- $version := "v1.0.0" }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: IPAMProvider
metadata:
  name: in-cluster
spec:
  version: {{ $version }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-ipam-in-cluster-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/cluster-api-ipam-in-cluster-controller:{{ $version }}
  {{- end }}
