apiVersion: k0rdent.mirantis.com/v1beta1
kind: Release
metadata:
  name: kcm-1-8-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  version: 1.8.0
  kcm:
    template: kcm-1-8-0
  regional:
    template: kcm-regional-1-8-0
  capi:
    template: cluster-api-1-12-5
  providers:
    - name: cluster-api-provider-k0sproject-k0smotron
      template: cluster-api-provider-k0sproject-k0smotron-1-10-3
    - name: cluster-api-provider-azure
      template: cluster-api-provider-azure-1-23-0
    - name: cluster-api-provider-vsphere
      template: cluster-api-provider-vsphere-1-15-1
    - name: cluster-api-provider-aws
      template: cluster-api-provider-aws-2-11-0
    - name: cluster-api-provider-openstack
      template: cluster-api-provider-openstack-0-13-0-mirantis-0
    - name: cluster-api-provider-docker
      template: cluster-api-provider-docker-1-12-5
    - name: cluster-api-provider-gcp
      template: cluster-api-provider-gcp-1-11-1
    - name: cluster-api-provider-ipam
      template: cluster-api-provider-ipam-1-1-0-rc-1
    - name: cluster-api-provider-infoblox
      template: cluster-api-provider-infoblox-0-1-0
    - name: cluster-api-provider-kubevirt
      template: cluster-api-provider-kubevirt-0-11-0
    - name: projectsveltos
      template: projectsveltos-1-8-0
