apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle
spec:
  collectors:
  - logs:
      namespace: ${NAMESPACE}
      name: logs/${NAMESPACE}
  - logs:
      namespace: projectsveltos
      name: logs/projectsveltos
