---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: PluggableProvider
metadata:
  name: cluster-api-provider-k0sproject-k0smotron
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: RemoteCluster
  clusterIdentityKinds:
    - Secret
  description: "K0smotron providers for Cluster API"
