---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: PluggableProvider
metadata:
  name: openstack
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: OpenStackCluster
  clusterIdentityKinds:
    - Secret
  description: "OpenStack infrastructure provider for Cluster API"
