---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: PluggableProvider
metadata:
  name: k0sproject-k0smotron
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: RemoteCluster
  clusterIdentityKinds:
    - Secret
  description: "k0smotron infrastructure provider for Cluster API"
