apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.singleArtifactSource.enabled }}
  image: {{ .Values.singleArtifactSource.registry}}/k0s
  etcd:
    image: "{{ .Values.singleArtifactSource.registry}}/etcd:v3.5.13"
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      network:
        provider: calico
        calico:
          mode: vxlan
      {{- if .Values.singleArtifactSource.enabled }}
      images:
        metricsserver:
          image: "{{ .Values.singleArtifactSource.registry}}/metrics-server"
        kubeproxy:
          image: "{{ .Values.singleArtifactSource.registry}}/kube-proxy"
        coredns:
          image: "{{ .Values.singleArtifactSource.registry}}/coredns"
        pause:
          image: "{{ .Values.singleArtifactSource.registry}}/pause"
        calico:
          cni:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-cni"
          node:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-node"
          kubecontrollers:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-kube-controllers"
      {{- end }}
      extensions:
        helm:
          {{- if not .Values.singleArtifactSource.enabled }}
          repositories:
            - name: vsphere-cpi
              url: https://kubernetes.github.io/cloud-provider-vsphere
            - name: mirantis
              url: https://charts.mirantis.com
          {{- end }}
          charts:
          - name: vsphere-cpi
            {{- if .Values.singleArtifactSource.enabled }}
            chartname: oci://{{ .Values.singleArtifactSource.registry}}/vsphere-cpi
            {{- else }}
            chartname: vsphere-cpi/vsphere-cpi
            {{- end }}
            version: 1.31.0
            order: 1
            namespace: kube-system
            values: |
              config:
                enabled: false
              daemonset:
                affinity: null
                {{- if .Values.singleArtifactSource.enabled }}
                image: {{ .Values.singleArtifactSource.registry }}/cloud-provider-vsphere
                {{- end }}
                tolerations:
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.kubernetes.io/not-ready
                    operator: Exists
                  - key: CriticalAddonsOnly
                    effect: NoExecute
                    operator: Exists
          - name: vsphere-csi-driver
            {{- if .Values.singleArtifactSource.enabled }}
            chartname: oci://{{ .Values.singleArtifactSource.registry}}/vsphere-csi-driver
            {{- else }}
            chartname: mirantis/vsphere-csi-driver
            {{- end }}
            version: 0.0.3
            order: 2
            namespace: kube-system
            values: |
              vcenterConfig:
                enabled: false
              controller:
                nodeAffinity: null
              node:
                kubeletPath: /var/lib/k0s/kubelet
              defaultStorageClass:
                enabled: true
              images:
                driver:
                  {{- if .Values.singleArtifactSource.enabled }}
                  repo: {{ .Values.singleArtifactSource.registry }}/driver
                  {{- end }}
                  tag: v3.1.2
                syncer:
                  {{- if .Values.singleArtifactSource.enabled }}
                  repo: {{ .Values.singleArtifactSource.registry }}/syncer
                  {{- end }}
                  tag: v3.1.2
                {{- if .Values.singleArtifactSource.enabled }}
                nodeDriverRegistrar:
                  repo: {{ .Values.singleArtifactSource.registry }}/csi-node-driver-registrar
                csiAttacher:
                  repo: {{ .Values.singleArtifactSource.registry }}/csi-attacher
                csiResizer:
                  repo: {{ .Values.singleArtifactSource.registry }}/csi-resizer
                csiProvisioner:
                  repo: {{ .Values.singleArtifactSource.registry }}/csi-provisioner
                csiSnapshotter:
                  repo: {{ .Values.singleArtifactSource.registry }}/csi-snapshotter
                livenessProbe:
                  repo: {{ .Values.singleArtifactSource.registry }}/livenessprobe
                {{- end }}
