apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: 3
  # dirty hack
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.singleArtifactSource.enabled }}
  image: {{ .Values.singleArtifactSource.registry}}/k0s
  etcd:
    image: "{{ .Values.singleArtifactSource.registry}}/etcd:v3.5.13"
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      network:
        provider: calico
        calico:
          mode: ipip
      {{- if .Values.singleArtifactSource.enabled }}
      images:
        metricsserver:
          image: "{{ .Values.singleArtifactSource.registry}}/metrics-server"
        kubeproxy:
          image: "{{ .Values.singleArtifactSource.registry}}/kube-proxy"
        coredns:
          image: "{{ .Values.singleArtifactSource.registry}}/coredns"
        pause:
          image: "{{ .Values.singleArtifactSource.registry}}/pause"
        calico:
          cni:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-cni"
          node:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-node"
          kubecontrollers:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-kube-controllers"
      {{- end }}
      extensions:
        helm:
          {{- if not .Values.singleArtifactSource.enabled }}
          repositories:
            - name: mirantis
              url: https://charts.mirantis.com
            - name: aws-ebs-csi-driver
              url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          {{- end }}
          charts:
          - name: aws-cloud-controller-manager
            namespace: kube-system
            {{- if .Values.singleArtifactSource.enabled }}
            chartname: oci://{{ .Values.singleArtifactSource.registry}}/aws-cloud-controller-manager
            {{- else }}
            chartname: mirantis/aws-cloud-controller-manager
            {{- end }}
            version: "0.0.9"
            values: |
              image:
                {{- if .Values.singleArtifactSource.enabled }}
                repository: {{ .Values.singleArtifactSource.registry }}
                {{- end }}
                tag: v1.30.3
              args:
                - --v=2
                - --cloud-provider=aws
                - --cluster-cidr={{ first .Values.clusterNetwork.pods.cidrBlocks }}
                - --allocate-node-cidrs=true
                - --cluster-name={{ include "cluster.name" . }}
              cloudConfig:
                enabled: true
                global:
                  KubernetesClusterID: {{ required ".Values.managementClusterName is required on AWS hosted deployment" .Values.managementClusterName }}
              # Removing the default `node-role.kubernetes.io/control-plane` node selector
              # TODO: it does not work
              nodeSelector:
                node-role.kubernetes.io/control-plane: null
          - name: aws-ebs-csi-driver
            namespace: kube-system
            {{- if .Values.singleArtifactSource.enabled }}
            chartname: oci://{{ .Values.singleArtifactSource.registry}}/aws-ebs-csi-driver
            {{- else }}
            chartname: aws-ebs-csi-driver/aws-ebs-csi-driver
            {{- end }}
            version: 2.33.0
            values: |
              {{- if .Values.singleArtifactSource.enabled }}
              image:
                repository: {{ .Values.singleArtifactSource.registry }}
              sidecars:
                provisioner:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                attacher:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                snapshotter:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                livenessProbe:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                resizer:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                nodeDriverRegistrar:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
                volumemodifier:
                  image:
                    repository: {{ .Values.singleArtifactSource.registry }}
              {{- end }}
              defaultStorageClass:
                enabled: true
              node:
                kubeletPath: /var/lib/k0s/kubelet
