apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-gcp
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: GCPCluster
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: GCPManagedCluster
  clusterIdentityKinds:
    - Secret
  description: "GCP infrastructure provider for Cluster API"
