apiVersion: lib.projectsveltos.io/v1beta1
kind: SveltosCluster
metadata:
  name: {{ include "cluster.name" . }}
  {{- if .Values.clusterLabels }}
  labels: {{- toYaml .Values.clusterLabels | nindent 4}}
    helm.toolkit.fluxcd.io/name: {{ .Release.Name }}
    helm.toolkit.fluxcd.io/namespace: {{ .Release.Namespace }}
  {{- end }}  
spec:
  consecutiveFailureThreshold: {{ .Values.consecutiveFailureThreshold }}
  kubeconfigName: {{ .Values.clusterIdentity.name }}
