apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k0rdent.mirantis.com/aggregate-to-global-admin: "true"
  name: {{ include "kcm.fullname" . }}-providerinterfaces-editor-role
rules:
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - providerinterfaces
  - providerinterfaces/status
  verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
