apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-secrets-editor-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-admin: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
