apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-servicetemplatechains-creator-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-admin: "true"
rules:
  - apiGroups:
      - k0rdent.mirantis.com
    resources:
      - servicetemplatechains
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
      - create
      - delete
  - apiGroups:
      - k0rdent.mirantis.com
    resources:
      - servicetemplates
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
