apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-servicetemplates-creator-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-admin: "true"
rules:
  - apiGroups:
      - k0rdent.mirantis.com
    resources:
      - servicetemplates
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
      - create
      - delete
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmcharts
      - helmrepositories
    verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
