
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOManagedMachinePool
metadata:
  name: {{ include "machinepool.user.name" . }}
spec:
  resources:
    - apiVersion: containerservice.azure.com/v1api20231001
      kind: ManagedClustersAgentPool
      metadata:
        annotations:
          serviceoperator.azure.com/credential-from: {{ .Values.clusterIdentity.name }}
          meta.helm.sh/release-name: {{ .Release.Name }}
          meta.helm.sh/release-namespace: {{ .Release.Namespace }}
        labels:
          helm.toolkit.fluxcd.io/name: {{ .Release.Name }}
          helm.toolkit.fluxcd.io/namespace: {{ .Release.Namespace }}
        name: {{ include "machinepool.user.name" . }}
      spec:
        azureName: userpool
        {{- if .Values.machinePools.user.autoscaling.enabled }}
        enableAutoScaling: {{ .Values.machinePools.user.autoscaling.enabled }}
        maxCount: {{ .Values.machinePools.user.autoscaling.maxCount }}
        minCount: {{ .Values.machinePools.user.autoscaling.minCount }}
        {{- end }}
        enableNodePublicIP: {{ .Values.machinePools.user.enableNodePublicIP }}
        maxPods: {{ .Values.machinePools.user.maxPods }}
        mode: User
        {{- with .Values.machinePools.user.nodeLabels }}
        nodeLabels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.machinePools.user.nodeTaints }}
        nodeTaints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        osDiskSizeGB: {{ .Values.machinePools.user.osDiskSizeGB }}
        owner:
          name: {{ include "cluster.name" . }}
        type: {{ .Values.machinePools.user.type }}
        vmSize: {{ .Values.machinePools.user.vmSize }}
