apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
spec:
  {{- with .Values.clusterNetwork }}
  clusterNetwork:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: AzureASOManagedControlPlane
    name: {{ include "cluster.name" .  }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: AzureASOManagedCluster
    name: {{ include "cluster.name" . }}
