apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kcm.fullname" . }}-controller-manager
  labels:
    control-plane: {{ include "kcm.fullname" . }}-controller-manager
  {{- include "kcm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: {{ include "kcm.fullname" . }}-controller-manager
    {{- include "kcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: {{ include "kcm.fullname" . }}-controller-manager
      {{- include "kcm.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    {{ $tel := .Values.telemetry -}}
    {{ $isLocalTelemetry := eq $tel.mode "local" -}}
    {{ $baseDir := default "/var/lib/telemetry" $tel.local.baseDir -}}
    {{ $vol := $tel.local.volume -}}
    spec:
      {{- if $isLocalTelemetry }}
      initContainers:
        - name: telemetry-data-permissions
          image: busybox:latest
          command: ["sh","-c","chown -R 65532:65532 {{ $baseDir }} || true"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              add: [CHOWN]
              drop: [ALL]
          volumeMounts:
            - name: telemetry-storage
              mountPath: {{ $baseDir }}
      {{- end }}
      containers:
      - args:
        - --templates-repo-url={{ .Values.controller.templatesRepoURL }}
        - --global-registry={{ .Values.controller.globalRegistry }}
        - --global-k0s-url={{ .Values.controller.globalK0sURL }}
        - --insecure-registry={{ .Values.controller.insecureRegistry }}
        {{- if .Values.controller.registryCredsSecret }}
        - --registry-creds-secret={{ .Values.controller.registryCredsSecret }}
        {{- end }}
        {{- if .Values.controller.k0sURLCertSecret }}
        - --k0s-url-cert-secret-name={{ .Values.controller.k0sURLCertSecret }}
        {{- end }}
        {{- if .Values.controller.registryCertSecret }}
        - --registry-cert-secret-name={{ .Values.controller.registryCertSecret }}
        {{- end }}
        - --create-management={{ .Values.controller.createManagement }}
        - --create-access-management={{ .Values.controller.createAccessManagement }}
        - --create-release={{ .Values.controller.createRelease }}
        - --create-templates={{ .Values.controller.createTemplates }}
        - --validate-cluster-upgrade-path={{ .Values.controller.validateClusterUpgradePath }}
        - --enable-telemetry={{ .Values.controller.enableTelemetry }}
        - --enable-webhook={{ .Values.admissionWebhook.enabled | default false }}
        - --webhook-port={{ .Values.admissionWebhook.port }}
        - --webhook-cert-dir={{ .Values.admissionWebhook.certDir }}
        {{- range $key, $value := .Values.controller.logger }}
        {{- if not (eq (printf "%s" $value) "") }}
        - --zap-{{ $key }}={{ $value }}
        {{- end }}
        {{- end }}
        - --telemetry-mode={{ $tel.mode }}
        - --telemetry-concurrency={{ $tel.concurrency }}
        - --telemetry-interval={{ $tel.interval }}
        - --telemetry-jitter={{ $tel.jitter }}
        {{- if $isLocalTelemetry }}
        - --telemetry-base-dir={{ $baseDir }}
        {{- end }}
        - --pprof-bind-address={{ .Values.controller.debug.pprofBindAddress }}
        {{- if .Values.controller.enableSveltosExpiredCtrl }}
        - --enable-sveltos-expire-ctrl={{ .Values.controller.enableSveltosExpiredCtrl }}
        {{- end }}
        {{- if .Values.controller.defaultHelmTimeout }}
        - --default-helm-timeout={{ .Values.controller.defaultHelmTimeout }}
        {{- end }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.admissionWebhook.enabled }}
        ports:
        - containerPort: {{ .Values.admissionWebhook.port }}
          name: {{ include "kcm.webhook.portName" . }}
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.resources | nindent 10 }}
        securityContext: {{ toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- $needMounts := or .Values.admissionWebhook.enabled $isLocalTelemetry }}
        {{- if $needMounts }}
        volumeMounts:
        {{- if .Values.admissionWebhook.enabled }}
          - mountPath: {{ .Values.admissionWebhook.certDir }}
            name: cert
            readOnly: true
        {{- end }}
        {{- if $isLocalTelemetry }}
          - mountPath: {{ $baseDir }}
            name: telemetry-storage
            readOnly: false
        {{- end }}
        {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "kcm.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- $needVolumes := or .Values.admissionWebhook.enabled $isLocalTelemetry }}
      {{- if $needVolumes }}
      volumes:
      {{- if .Values.admissionWebhook.enabled }}
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "kcm.webhook.certName" . }}
      {{- end }}
      {{- if $isLocalTelemetry }}
        - name: telemetry-storage
          persistentVolumeClaim:
            claimName: {{ include "kcm.telemetry.claimName" . }}
      {{- end }}
      {{- end }}
