apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcm.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: {{ include "kcm.fullname" . }}-controller-manager
  {{- include "kcm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: {{ include "kcm.fullname" . }}-controller-manager
  {{- include "kcm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}
