{{- if .Values.projectsveltos.crds.enabled}}
{{- range $path, $_ := .Files.Glob "projectsveltos-crds/*.yaml" }}
{{- $content := $.Files.Get $path | fromYaml }}
apiVersion: {{ $content.apiVersion }}
kind: {{ $content.kind }}
metadata:
  name: {{ $content.metadata.name }}
spec: {{ $content.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}