{{- if .Values.projectsveltos.crds.enabled}}
{{- $labels := include "kcm.labels" . }}
{{- $annotations := include "kcm.annotations" . }}
{{- range $path, $_ := .Files.Glob "projectsveltos-crds/*.yaml" }}
{{- $content := $.Files.Get $path | fromYaml }}
apiVersion: {{ $content.apiVersion }}
kind: {{ $content.kind }}
metadata:
  name: {{ $content.metadata.name }}
  labels:
    {{ $labels | nindent 4 }}
  annotations:
    {{ $annotations | nindent 4 }}
spec: {{ $content.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}