apiVersion: v1
kind: ConfigMap
metadata:
  name: providers
data:
  {{- $files := .Files }}
  {{- range $path, $_ :=  .Files.Glob  "files/providers/*.yml" }}
  {{ base $path }}: |-
    {{ $files.Get $path | nindent 4 }}
  {{- end }}
