apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kcm.fullname" . }}-controller-manager
  labels:
  {{- include "kcm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
