nameOverride: ""
fullnameOverride: ""

admissionWebhook:
  enabled: false
  port: 9443
  certDir: "/tmp/k8s-webhook-server/serving-certs/"

controller:
  defaultRegistryURL: "oci://ghcr.io/k0rdent/kcm/charts"
  registryCredsSecret: ""
  insecureRegistry: false
  createManagement: true
  createAccessManagement: true
  createRelease: true
  createTemplates: true
  enableTelemetry: true

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

image:
  repository: ghcr.io/k0rdent/kcm/controller
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicas: 1

serviceAccount:
  annotations: {}

kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP

# Subcharts
cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false

flux2:
  enabled: true
  policies:
    create: false
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
  helmController:
    container:
      additionalArgs:
        - --watch-label-selector=k0rdent.mirantis.com/managed=true
  sourceController:
    container:
      additionalArgs:
        - --watch-label-selector=k0rdent.mirantis.com/managed=true

cluster-api-operator:
  enabled: false
  resources:
    manager:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 150Mi

velero:
  enabled: true
  # example of enabling a plugin
  # initContainers:
  #   - name: velero-plugin-for-aws
  #     image: velero/velero-plugin-for-aws:v1.11.0
  #     imagePullPolicy: IfNotPresent
  #     volumeMounts:
  #       - mountPath: /target
  #         name: plugins
  metrics:
    enabled: false
  upgradeCRDs: false
  cleanUpCRDs: false
  credentials:
    useSecret: false
  snapshotsEnabled: false
  backupsEnabled: false
  deployNodeAgent: false
