apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: OpenStackCluster
  clusterIdentities:
    - group: ""
      version: v1
      kind: Secret
    - group: infrastructure.cluster.x-k8s.io
      version: v1alpha1
      kind: OpenStackClusterIdentity
      references:
        - group: ""
          version: v1
          kind: Secret
          nameFieldPath: spec.secretRef.name
          namespaceFieldPath: spec.secretRef.namespace
  description: "OpenStack infrastructure provider for Cluster API"
