apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: adopted-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: adopted-cluster-1-0-0
  credential: adopted-cluster-cred
  config:
    clusterLabels: {}
    clusterAnnotations: {}
