apiVersion: v1
data:
  value: ${KUBECONFIG_DATA}
kind: Secret
metadata:
  name: adopted-cluster-kubeconf
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: adopted-cluster-cred
  namespace: ${NAMESPACE}
spec:
  description: Adopted Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: adopted-cluster-kubeconf
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adopted-cluster-kubeconf-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
