apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: squizz-aws-dev
  namespace: ${NAMESPACE}
spec:
  config:
    controlPlane:
      instanceType: t3.xlarge
    controlPlaneNumber: 1
    publicIP: true
    region: us-west-2
    worker:
      instanceType: t3.xlarge
    workersNumber: 1
    installBeachHeadServices: false
  template: aws-standalone-cp
