apiVersion: v1
kind: Secret
metadata:
  name: docker-cluster-secret
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: docker-stub-credential
  namespace: ${NAMESPACE}
spec:
  description: Docker Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: docker-cluster-secret
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-cluster-credential-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
