apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: eks-dev
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  template: aws-eks-0-0-4
  credential: "aws-cluster-identity-cred"
  config:
    region: ${AWS_REGION}
    workersNumber: 1
