apiVersion: v1
kind: Secret
metadata:
  name: gcp-cloud-sa
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
data:
  # the secret key should always equal `credentials`
  credentials: ${GCP_B64ENCODED_CREDENTIALS}
type: Opaque
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: gcp-credential
  namespace: ${NAMESPACE}
spec:
  description: GCP Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: gcp-cloud-sa
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-cloud-sa-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
data:
  configmap.yaml: |
    {{- $$secret := (getResource "InfrastructureProviderIdentity") -}}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: gcp-cloud-sa
      namespace: kube-system
    type: Opaque
    data:
      cloud-sa.json: {{ index $$secret "data" "credentials" }}
