apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: hetzner-example
  namespace: default
spec:
  clusterTemplate:
    name: hetzner-standalone-cp
    values:
      region: "fsn1"
      sshKeyName: "my-ssh-key"
      clusterIdentity:
        name: "hcloud-token"
        kind: "HetznerClusterIdentity"
      
      controlPlaneNumber: 3
      workersNumber: 2
      
      controlPlane:
        serverType: "cx31"
        image: "ubuntu-22.04"
        rootVolume:
          size: 80
        placementGroup:
          enabled: true
          type: "spread"
      
      worker:
        serverType: "cx21"
        image: "ubuntu-22.04"
        rootVolume:
          size: 40
        placementGroup:
          enabled: true
          type: "spread"
      
      loadBalancer:
        enabled: true
        type: "lb11"
      
      network:
        cidrBlock: "10.0.0.0/16"
        subnetCidrBlock: "10.0.0.0/24"
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: hetzner-dev
  namespace: default
spec:
  clusterTemplate:
    name: hetzner-hosted-cp
    values:
      region: "fsn1"
      sshKeyName: "dev-ssh-key"
      clusterIdentity:
        name: "hcloud-dev-token"
        kind: "HetznerClusterIdentity"
      
      workersNumber: 2
      
      worker:
        serverType: "cx21"
        image: "ubuntu-22.04"
        rootVolume:
          size: 40
      
      loadBalancer:
        enabled: true
        type: "lb11"
      
      network:
        cidrBlock: "10.0.0.0/16"
        subnetCidrBlock: "10.0.0.0/24" 