apiVersion: hmc.mirantis.com/v1alpha1
kind: Management
metadata:
  name: hmc
spec:
  core:
    hmc:
      template: hmc
    capi:
      template: cluster-api
  providers:
    - template: k0smotron
    - template: cluster-api-provider-aws
      config:
        credentialsSecretName: aws-credentials
