---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-cloud-config
  namespace: ${NAMESPACE}
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: ${OS_AUTH_URL}
          application_credential_id: ${OS_APPLICATION_CREDENTIAL_ID}
          application_credential_secret: ${OS_APPLICATION_CREDENTIAL_SECRET}
        region_name: ${OS_REGION_NAME}
        interface: ${OS_INTERFACE}
        identity_api_version: ${OS_IDENTITY_API_VERSION}
        auth_type: ${OS_AUTH_TYPE}
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: openstack-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: OpenStack credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: openstack-cloud-config
    namespace: ${NAMESPACE}
