apiVersion: v1
data:
  value: ${PRIVATE_SSH_KEY_B64}
kind: Secret
metadata:
  name: remote-ssh-key
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: remote-cred
  namespace: ${NAMESPACE}
spec:
  description: Credentials for accessing remote machines
  identityRef:
    apiVersion: v1
    kind: Secret
    name: remote-ssh-key
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-ssh-key-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
