cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false

cluster-api-operator:
  enabled: false
  resources:
    manager:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 200m
        memory: 150Mi

velero:
  enabled: true
  fullnameOverride: velero # vmware-tanzu/velero#9023
  # example of enabling a plugin
  # initContainers:
  # - name: velero-plugin-for-aws
  #   image: velero/velero-plugin-for-aws:v1.11.0
  #   imagePullPolicy: IfNotPresent
  #   volumeMounts:
  #     - mountPath: /target
  #       name: plugins
  metrics:
    enabled: false
  upgradeCRDs: false
  cleanUpCRDs: false
  credentials:
    useSecret: false
  snapshotsEnabled: false
  backupsEnabled: false
  deployNodeAgent: false
