apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: {{ include "cluster.name" . }}
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  project: {{ .Values.project }}
  region: {{ .Values.region }}
  network:
    name: {{ .Values.network.name }}
    mtu: {{ .Values.network.mtu }}
  {{- if .Values.additionalLabels }}
  additionalLabels: {{- toYaml .Values.additionalLabels | nindent 4 }}
  {{- end }}
  credentialsRef:
    name: {{ .Values.clusterIdentity.name }}
    namespace: {{ .Values.clusterIdentity.namespace }}
