{{- if ne .Values.telemetry.mode "disabled" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcm-regional.fullname" . }}-leader-election-role
  labels: {{- include "kcm-regional.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kcm-regional.fullname" . }}-leader-election-rolebinding
  labels: {{- include "kcm-regional.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kcm-regional.fullname" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kcm-regional.fullname" . }}-telemetry'
  namespace: '{{ .Release.Namespace }}'
{{- end -}}
