{{- if ne .Values.telemetry.mode "disabled" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm-regional.fullname" . }}-telemetry-role
  labels: {{- include "kcm-regional.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments
  - clusterdeployments/finalizers
  - clusterdeployments/status
  - clustertemplates
  - clustertemplates/finalizers
  - clustertemplates/status
  - managements
  - managements/finalizers
  - managements/status
  - regions
  - regions/finalizers
  - regions/status
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/finalizers
  - clusters/status
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  - profiles/finalizers
  - profiles/status
  - clusterprofiles
  - clusterprofiles/finalizers
  - clusterprofiles/status
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
{{- end -}}
