apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.singleArtifactSource.enabled }}
  image: {{ .Values.singleArtifactSource.registry}}/k0s
  etcd:
    image: "{{ .Values.singleArtifactSource.registry}}/etcd:v3.5.13"
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      network:
        provider: calico
        calico:
          mode: vxlan
      {{- if .Values.singleArtifactSource.enabled }}
      images:
        metricsserver:
          image: "{{ .Values.singleArtifactSource.registry}}/metrics-server"
        kubeproxy:
          image: "{{ .Values.singleArtifactSource.registry}}/kube-proxy"
        coredns:
          image: "{{ .Values.singleArtifactSource.registry}}/coredns"
        pause:
          image: "{{ .Values.singleArtifactSource.registry}}/pause"
        calico:
          cni:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-cni"
          node:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-node"
          kubecontrollers:
            image: "{{ .Values.singleArtifactSource.registry}}/calico-kube-controllers"
      {{- end }}
      extensions:
        helm:
          {{- if not .Values.singleArtifactSource.enabled }}
          repositories:
            - name: mirantis
              url: https://charts.mirantis.com
            - name: azuredisk-csi-driver
              url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
          {{- end }}
          charts:
            - name: cloud-provider-azure
              namespace: kube-system
              {{- if .Values.singleArtifactSource.enabled }}
              chartname: oci://{{ .Values.singleArtifactSource.registry}}/cloud-provider-azure
              {{- else }}
              chartname: mirantis/cloud-provider-azure
              {{- end }}
              version: 1.31.2
              order: 1
              values: |
                cloudControllerManager:
                  cloudConfigSecretName: azure-cloud-provider
                  nodeSelector:
                    node-role.kubernetes.io/control-plane: "true"
                  {{- if .Values.singleArtifactSource.enabled }}
                  imageRepository: {{ .Values.singleArtifactSource.registry }}
                  {{- end }}
                  imageTag: v1.32.4
                cloudNodeManager:
                  imageTag: v1.32.4
                {{- if .Values.singleArtifactSource.enabled }}
                  imageRepository: {{ .Values.singleArtifactSource.registry }}
                {{- end }}
            - name: azuredisk-csi-driver
              namespace: kube-system
              {{- if .Values.singleArtifactSource.enabled }}
              chartname: oci://{{ .Values.singleArtifactSource.registry}}/azuredisk-csi-driver
              {{- else }}
              chartname: azuredisk-csi-driver/azuredisk-csi-driver
              {{- end }}
              version: 1.30.3
              order: 2
              values: |
                {{- if .Values.singleArtifactSource.enabled }}
                image:
                  baseRepo: {{ .Values.singleArtifactSource.registry }}
                {{- end }}
                controller:
                  cloudConfigSecretName: azure-cloud-provider
                node:
                  cloudConfigSecretName: azure-cloud-provider
                linux:
                  kubelet: "/var/lib/k0s/kubelet"
