name: Build and Unit Tests
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - '**.md'
  push:
    tags:
      - '*'

env:
  GO_VERSION: '1.22'

jobs:
  build:
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m0s
      - name: Verify all generated pieces are up-to-date
        run: make generate-all && git add -N . && git diff --exit-code
      - name: Unit tests
        run: |
          make test
      - name: Build HMC controller image
        run: |
          make docker-build