name: Release HMC

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push HMC controller image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            LD_FLAGS=-s -w -X github.com/Mirantis/hmc/internal/build.Version=${{ env.VERSION }} -X github.com/Mirantis/hmc/internal/telemetry.segmentToken=${{ secrets.SEGMENT_TOKEN }}
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/mirantis/hmc/controller:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare HMC chart
        run: VERSION="${{ env.VERSION }}" make hmc-chart-release
      - name: Push charts to GHCR
        run: REGISTRY_REPO="oci://ghcr.io/mirantis/hmc/charts" make helm-push

      - name: Prepare manifests
        run: make hmc-dist-release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(env.VERSION, '-') }}
          files: |
            dist/install.yaml
            templates/provider/hmc-templates/files/release.yaml
          draft: true
