name: Release KCM

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push KCM controller image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            LD_FLAGS=-s -w -X github.com/K0rdent/kcm/internal/build.Version=${{ env.VERSION }} -X github.com/K0rdent/kcm/internal/telemetry.segmentToken=${{ secrets.SEGMENT_TOKEN }}
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/k0rdent/kcm/controller:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare KCM chart
        run: VERSION="${{ env.VERSION }}" make kcm-chart-release
      - name: Push charts to GHCR
        run: REGISTRY_REPO="oci://ghcr.io/k0rdent/kcm/charts" make helm-push

      - name: Prepare manifests
        run: make kcm-dist-release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(env.VERSION, '-') }}
          files: |
            dist/install.yaml
            templates/provider/kcm-templates/files/release.yaml
          draft: true

      - name: Build airgap bundle
        env:
          IMG: 'ghcr.io/k0rdent/kcm/controller:${{ env.VERSION }}'
        run: |
          make airgap-package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Upload airgap bundle
        run: aws s3 cp bin/kcm-airgap-${{ env.VERSION }}.tgz s3://binary2a-mirantis-com/kcm-airgap-${{ env.VERSION }}.tgz
