name: Build and Test

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    tags:
      - '*'
    paths-ignore:
      - 'config/**'
      - '**.md'

env:
  GO_VERSION: '1.22'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m0s
      - name: Verify all generated pieces are up-to-date
        run: make generate-all && git add -N . && git diff --exit-code
      - name: Unit tests
        run: |
          make test
      - name: Build
        run: |
          make build
      - name: Image build
        run: |
          make docker-build
  e2etest:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Run E2E tests
        run: |
          make test-e2e
      - name: Get test logs
        run: |
          kubectl logs -n hmc-system -l app=e2e-test > test/e2e/e2e-test.log
          ./bin/clusterctl describe cluster --show-conditions=all > test/e2e/clusterctl.log
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test/e2e/*.log
