name: Build and Test

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - '**.md'

env:
  GO_VERSION: '1.22'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m0s
      - name: Verify all generated pieces are up-to-date
        run: make generate-all && git add -N . && git diff --exit-code
      - name: Unit tests
        run: |
          make test
      - name: Build
        run: |
          make build
      - name: Image build
        run: |
          make docker-build
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Run E2E tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          SOME_TEST_SECRET: ${{ secrets.CI_TEST_SECRET }}
          AWS_REGION: 'us-west-2'
        run: |
          echo $SOME_TEST_SECRET
          make test-e2e
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test/e2e/*.log
