name: E2E Tests

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - release-*
    paths-ignore:
      - 'config/**'
      - '**.md'
env:
  GO_VERSION: '1.22'

jobs:
  e2etest:
    name: E2E Tests
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-e2e')
    env:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
        go-version: ${{ env.GO_VERSION }}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Run E2E tests
        run: |
          make test-e2e
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
        name: test-logs
        path: |
          test/e2e/*.log
